### ISSUE TITLE
output images

### ISSUE THREAD

**Issue by apz719** [Thanos-DB/FullyConvolutionalTransformer#10]
Hi.
firstly, you have done a great job thanks for your code.
is it possible to save the output images? how can I save the predicted images?

**Comment by Thanos-DB** [comment]
Hi apz719,

it is sertainly possible and there are many ways to do it.
You can try `plt.imsave('image.png', img)`. Just pay attention to the shape of the predicted masks and create a loop to go through all of them.

Thanos
