### ISSUE TITLE
Can you provide the online download address of Spleen Segmentation Dataset?

### ISSUE THREAD

**Issue by xiaoc57** [Thanos-DB/FullyConvolutionalTransformer#11]
Can you provide the online download address of Spleen Segmentation Dataset?

**Comment by Thanos-DB** [comment]
Hi 57xiaoc,

the link is [https://drive.google.com/drive/folders/1HqEgzS8BV2c7xYNrZdEAnrHk7osJJ--2](url)

**Comment by 57xiaoc** [comment]
@Thanos-DB I know this website, but there is no label in the test image, where can I get this label? Or can I only get the final result by submitting the competition?

**Comment by Thanos-DB** [comment]
To my knowledge there are no ground truth masks for the test set.
