### ISSUE TITLE
ResourceExhaustedError:

### ISSUE THREAD

**Issue by adnankhalid7454** [Thanos-DB/FullyConvolutionalTransformer#13]
ResourceExhaustedError:  OOM when allocating tensor with shape[2,256,256,32] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node model_3/up_sampling2d_27/resize/ResizeNearestNeighbor (defined at C:\Users\adnan\AppData\Local\Temp\ipykernel_3992\1459390362.py:4) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_train_function_118790]

Function call stack:
train_function

I am using RtX2070 GPU for this Tensorflow model. But I am facing this issue after decreasing the batch size. Can you figure out the issue? Thank you

**Comment by Thanos-DB** [comment]
Hi Adnan,

it seems your GPU does not have enough memory. If i am not wrong your 2070 has 8GB of VRAM. First before changing anything in the model, have you tried with batch size of 1? I suspect it will still give you the same error but give it a try.
If this fails then reduce the numbers of filters per block changing this `filters = [16, 32, 64, 128, 384, 128, 64, 32, 16]` to maybe this `filters = [8, 16, 32, 64, 128, 64, 32, 16, 8]`. If this also fails you can play around till you find the one that fits in your GPU.
Other than that you could also get rid of the multi-input and/or multi-output strategies used. So, maybe one input, one output.

I have used this `filters = [16, 32, 64, 128, 384, 128, 64, 32, 16]` with batch size of 2 using an RTX 3080 with 10GB and it was working fine.

BR
Thanos

**Comment by adnankhalid7454** [comment]
thank you for your message and explanation of training the model in Low resource environment. 

Secondly, You only provide the script for training the mode. Can you please provide the script that combines all slices for single-volume prediction? The combined results later use to visualize the results in Nifti File format. Thank you

**Comment by Thanos-DB** [comment]
Give this a try. Note that in the function i use the ground truth masks `y_val_cat` because i do not have any predictions at hand but you can use `pred[2]` and the appropriate header, affine etc.

```python
def generate_files(pred, cfg, aff, hea):
    
    # 4 masks to one
    pred = np.argmax(pred, axis=-1)
    
    c = 0 # for affine and header
    
    uniq = np.unique(cfg)
    for u in uniq:
        # find all images from same patient and same ED/ES
        idx = np.where(np.array(cfg)==u)
        
        p = pred[idx]
        
        # reshape to original dimensions
        p = np.moveaxis(p, 0, -1)
        p = cv2.resize(p, (hea[c]["dim"][2], hea[c]["dim"][1]), interpolation=cv2.INTER_NEAREST)
       
        new_nif = nib.Nifti1Image(p, affine=aff[c], header=hea[c])
        # save
        new_nif.to_filename("D:/Data/Automated Cardiac Diagnosis Challenge (ACDC)/predictions/" + u + ".nii.gz")
        
        # track progress
        print(u)    
        
        c += 1 # for the next affine and header

    return None
# example

# validation
acdc_data, val_afn, val_hdr = get_acdc(acdc_data_validation)
X_val, y_val, info_val = acdc_data[0], acdc_data[1], acdc_data[2]

y_val_cat = convert_masks(y_val)

generate_files(y_val_cat, info_val, val_afn, val_hdr)
```

**Comment by adnankhalid7454** [comment]
Thank you for your prompt reply. Can you suggest the best way to combine all the predicted classes [0,1,2,3] into single slice format? or if you can have any method already implemented, it will be a great help.

**Comment by Thanos-DB** [comment]
The code above takes care of it. So it expects that you give all the slices. Try this `print(y_val_cat.shape)` and you ll see the shape you have to provide. Then the line `pred = np.argmax(pred, axis=-1)` will combine the different slices for you.

**Comment by adnankhalid7454** [comment]
Hi Thanos, 
Can you please share some of your thoughts on data normalization in ACDC? 
Is data normalization range [0-1] will be helpful for this problem? I didn't see any approach you followed for data normalization n these experiments. Thank you and looking forward to your valuable comments.

**Comment by Thanos-DB** [comment]
Hi Adnan,

in our experiments using normalization or standardization did not help improve the metrics. In theory if you are using the exact same model with ACDC it should not improve your metrics too. If you have a different model, for instance without layernorm layers, that is a different story.

Thanos
