### ISSUE TITLE
Can you provide code to read the Synapse dataset using this model?

### ISSUE THREAD

**Issue by zww597** [Thanos-DB/FullyConvolutionalTransformer#17]
Can you provide code to read the Synapse dataset using this model?If possible, please email me at 597487013@qq.com. Thank you very much

**Comment by Thanos-DB** [comment]
I think its best to ask the authors of TransUnet, if possible to provide you with their files.
We also asked them and they were happy to help.

I am not able to redistribute the files they have sent so go directly to them.

-Thanos

**Comment by zww597** [comment]
Ok, thank you for your advice and have a nice life!




Alone.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Thanos-DB/FullyConvolutionalTransformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月30日(星期三) 下午5:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Thanos-DB/FullyConvolutionalTransformer] Can you provide code to read the Synapse dataset using this model? (Issue #17)





 
I think its best to ask the authors of TransUnet, if possible to provide you with their files.
 We also asked them and they were happy to help.
 
I am not able to redistribute the files they have sent so go directly to them.
 
-Thanos
