### ISSUE TITLE
Pretrained Models?

### ISSUE THREAD

**Issue by sumi890** [Thanos-DB/FullyConvolutionalTransformer#2]
Hi, 
first of all, you have done a great job....Hats off
can you please provide the pre-trained models of your experiments?
Thanks!

**Comment by Thanos-DB** [comment]
Hi sumi890,

thank you for the interest!
I ll do it towards the end of the week if it s ok with you because i have a deadline to catch.

BR
Thanos

**Comment by sumi890** [comment]
Hi Thanos,

Yes sure I am ok with that, and best of luck!

BR
Sumayya

**Comment by Thanos-DB** [comment]
Hi sumi890,

I am sorry for delaying this much. Here (https://gla-my.sharepoint.com/:f:/g/personal/a_tragakis_1_research_gla_ac_uk/EpyRwXVsbXxEmTaEjl-OuFYBKzdLVyH5JOllDTqxZQt4Uw?e=ELNbEq) you can find the weights for the given notebook.

BR
Thanos

**Comment by sumi890** [comment]
Thanks a lot Thanos!
