### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ZCL7** [Thanos-DB/FullyConvolutionalTransformer#20]
Dear Thanos,
    I am sorry to disturb you in your busy schedule.I'm a postgraduate student from Shandong,China.
My research direction is also heart segmentation，I also used the ACDC database. Your paper gives me great inspiration. I am currently facing some graduation troubles. I see that the source code you posted is not complete, and I know it involves confidentiality. If possible,can you send me the source code? I will only use it for my graduation research and will not use it for any for-profit activities.
    No matter whether you agree or not, best wishes to you. I would appreciate it if you could help me. My email is 15194109661@163.com
Thanks and regards.
Sincerely,
Zhai chunlin
2023/10/11

**Comment by Thanos-DB** [comment]
Hi @ZCL7 

everything you need is uploaded. There is a notebook that you can run and it will duplicate the results of the paper.

BR
Thanos
