### ISSUE TITLE
some questions about dice in ACDC dataset

### ISSUE THREAD

**Issue by yinguanchun** [Thanos-DB/FullyConvolutionalTransformer#22]
In synapse dataset, all metrics is in 2D slices of synapse dataset. But in ACDC dataset, the dice of nnFormer is 91.78,I konw this result  appeares in  3D data ，and your method is  93.02, so has your  model  on 2D slices  outperformed other models on 3D data ?

**Comment by Thanos-DB** [comment]
Hi @yinguanchun,

our model has outperformed other 3D models as can be seen in Table 4 in the paper. This is on the test set and the evaluation took place on the online platform that at that point was still active.
