### ISSUE TITLE
environment configuration

### ISSUE THREAD

**Issue by Susu0812** [Thanos-DB/FullyConvolutionalTransformer#24]
Hello author, I am very interested in your paper and experiments. Could you please provide a detailed environment configuration file, proportional to requirements.txt. I see that your readme doesn't give too many operational details for experimental reproduction. Thank you very much if you can reply

**Comment by Thanos-DB** [comment]
Hi @Susu0812, 

you can check issue  #21. It has a requirements file.
Alternatively, in the readme we provide a docker image.

BR
Thanos
