### ISSUE TITLE
which dataset did you use for this code?

### ISSUE THREAD

**Issue by tphankr** [Thanos-DB/FullyConvolutionalTransformer#6]
Thank you for your code. Can I download a dataset to work with your code? Thanks.

**Comment by Thanos-DB** [comment]
Hi tphankr,

thank you for checking our work. All the datasets used in our paper are freely available and can be downloaded by everyone. Just google them and you should not have any problems finding them.

BR
Thanos

**Comment by JosephKKim** [comment]
Hi Thanos, I also want to ask you about the ACDC dataset. It seems like that they are providing 100 training samples of patients and 50 test samples, but in your paper you said that you used 70-10-20 split. So can you specify more information about the dataset generation? 
Maybe patient number for each split would help me with reproducing the results.

Thanks!

**Comment by Thanos-DB** [comment]
Hi Joseph,

the splits can be seen below. This is a random split (a piece of code was written to split the patients) but we also trained the model using 5-Fold Cross Validation which also resulted in SOTA results.

test: ['patient100', 'patient095', 'patient094', 'patient087', 'patient082', 'patient080', 'patient079', 'patient076', 'patient062', 'patient057', 'patient041', 'patient036', 'patient029', 'patient028', 'patient026', 'patient021', 'patient019', 'patient016', 'patient013', 'patient001']

train: ['patient099', 'patient097', 'patient096', 'patient093', 'patient092', 'patient091', 'patient090', 'patient089', 'patient088', 'patient086', 'patient085', 'patient084', 'patient081', 'patient078', 'patient077', 'patient075', 'patient074', 'patient073', 'patient072', 'patient071', 'patient070', 'patient069', 'patient068', 'patient067', 'patient066', 'patient065', 'patient064', 'patient061', 'patient058', 'patient056', 'patient055', 'patient054', 'patient053', 'patient052', 'patient051', 'patient050', 'patient048', 'patient047', 'patient046', 'patient045', 'patient044', 'patient043', 'patient042', 'patient040', 'patient039', 'patient038', 'patient037', 'patient035', 'patient034', 'patient033', 'patient032', 'patient031', 'patient030', 'patient027', 'patient025', 'patient024', 'patient023', 'patient022', 'patient020', 'patient018', 'patient015', 'patient014', 'patient009', 'patient008', 'patient007', 'patient006', 'patient005', 'patient004', 'patient003', 'patient002']

validation: ['patient098', 'patient083', 'patient063', 'patient060', 'patient059', 'patient049', 'patient017', 'patient012', 'patient011', 'patient010']

**Comment by 15634354109** [comment]
Hi Thanos，does the ACDC data downloaded from the official website only need to be divided into training sets, verification sets, and test sets, and does it not need to undergo further preprocessing

**Comment by 15634354109** [comment]
Hi Thanos，I classified the data according to your method，but the code for get the ACDC data module always reports an error（AxisError: axis 3 is out of bounds for array of dimension 2）.

**Comment by Thanos-DB** [comment]
Hi 15634354109,
are you using Pytorch or Tensorflow? Where exactly in the code are you getting this error?

**Comment by 15634354109** [comment]
Hi Thanos，
I use Tensorflow.When I run the code that "Get data ACDC" from the main_ACDC_92.84.ipynb，will report an error:（AxisError: axis 3 is out of bounds for array of dimension 2）.

**Comment by Thanos-DB** [comment]
Check your paths. Are you sure you are using the correct path? Also, something that happened to me before is that i was using the correct path and everything was setup correctly but i did not have the rights to use the folder (this was in Ubuntu). I was getting the exact same error as you.

You can troubleshoot using the following code to see the paths (it was generated using ChatGPT but i tested it and it works)
```python
import os
path = '/path/to/directory'
for root, dirs, files in os.walk(path, topdown=False):
    # Print all files in the directory
    for name in files:
        print(os.path.join(root, name))
    # Print all directories in the directory
    for name in dirs:
        print(os.path.join(root, name))
```

I found out that i did not have the rights to use the folder using `os.chdir(path)` where `path` is the path to the dataset and got the following `PermissionError: [Errno 13] Permission denied: '/nfs/Automated Cardiac Diagnosis Challenge (ACDC)'` but the `get_acdc()` function was giving me the same error as yours.
