### ISSUE TITLE
number of  filters and attention heads 

### ISSUE THREAD

**Issue by lcx1505900610** [Thanos-DB/FullyConvolutionalTransformer#7]
in papers number of filters per stage is [16, 32, 64, 128, 384, 128, 64, 32, 16], number of attention
heads per stage is[2, 4, 8, 12, 16, 12, 8, 4, 2].
but in code,is different.
i want to train  Synapse,which should i use att_heads = [2, 2, 2, 2, 2, 2, 2, 2, 2],filters = [8, 16, 32, 64, 128, 64, 32, 16, 8] ?or filters = [32, 64, 128, 256, 512, 256, 128, 64, 32]

**Comment by Thanos-DB** [comment]
Hi lcx1505900610,

thank you for using our work.
Different datasets have different settings. Due to the limited number of pages of the paper we could not describe everything and document all the settings.
For Synapse we used:
```
att_heads = [2, 2, 2, 2, 2, 2, 2, 2, 2]
filters = [32, 64, 128, 256, 512, 256, 128, 64, 32]
```

BR
Thanos
