### ISSUE TITLE
Loading the model

### ISSUE THREAD

**Issue by OmarKhaled1504** [Thanos-DB/FullyConvolutionalTransformer#8]
When i save the model using `torch.save(model.state_dict(), "path/name.pt")` then load it using `model.load_state_dict(torch.load("path/name.p"))` to continue training, it starts training from the beginnig, is there another way to achieve what i want to do? as i see in your code you save the model using the same method.

**Comment by Thanos-DB** [comment]
Hi Omar,

first of all check the extensions you are using. It seems to me that you are trying to load `name.**p**` whereas you are saving `name.**pt**`. Maybe you are loading some old file and not the one you really want. Other than that i do not resume training after  saving the weights, i just save the weights in case i want to evalutate it later. If you want to resume training this is not the correct way to do it. This https://pytorch.org/tutorials/recipes/recipes/saving_and_loading_a_general_checkpoint.html is a good start on how to do it and also this https://discuss.pytorch.org/t/loading-a-saved-model-for-continue-training/17244 is an explanation of why this happens.

BR
Thanos

**Comment by OmarKhaled1504** [comment]
Hi, thank you for your help, changing my saving method worked.
